// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE56VqtGTdBtzpduXME3d427EUy0wL7ZU',
    appId: '1:587598364054:web:91380868f957f468f271b7',
    messagingSenderId: '587598364054',
    projectId: 'finflow-00',
    authDomain: 'finflow-00.firebaseapp.com',
    storageBucket: 'finflow-00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN6tsHwuY6Qs_vFQUeOQMzCmOA8ucYs38',
    appId: '1:587598364054:android:9562fa1724f7a3d9f271b7',
    messagingSenderId: '587598364054',
    projectId: 'finflow-00',
    storageBucket: 'finflow-00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDycw_UbVJkcHqqb-UMKXBCiBEM_cAJjN8',
    appId: '1:587598364054:ios:7fe63b3a313bccbcf271b7',
    messagingSenderId: '587598364054',
    projectId: 'finflow-00',
    storageBucket: 'finflow-00.firebasestorage.app',
    iosClientId: '587598364054-rn6bv9bfe14u3o9s6fu0v8ia75db4u7g.apps.googleusercontent.com',
    iosBundleId: 'com.sun.finflow',
  );
}
